// <auto-generated />
using System;
using CodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace UT02_02_CodeFirst.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241004084735_Seeder3car")]
    partial class Seeder3car
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UT02_02_CodeFirst.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Car");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Seat",
                            Model = "Panda",
                            Price = 15000m,
                            ReleaseDate = new DateTime(2024, 10, 4, 9, 47, 34, 996, DateTimeKind.Local).AddTicks(3978)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Seat",
                            Model = "Ibiza",
                            Price = 16000m,
                            ReleaseDate = new DateTime(2024, 10, 4, 9, 47, 34, 996, DateTimeKind.Local).AddTicks(4025)
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Audi",
                            Model = "Franchesco",
                            Price = 20000m,
                            ReleaseDate = new DateTime(2024, 10, 4, 9, 47, 34, 996, DateTimeKind.Local).AddTicks(4028)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
